apps/account/urls.py
from apps.account import views
from django.urls import path

app_name = 'account'

urlpatterns = [
    path('agree/', views.agree, name='agree'),
    path('register/', views.register, name='register'),
    path('modify/', views.modify, name='modify')
]

apps/index/urls.py
from django.urls import path, include
from apps.index import views
from django.contrib.auth import views as auth_views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='login_form.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('choose_function/', views.choose_function, name='choose_function')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.index.urls')),
    path('account/', include('apps.account.urls')),
    path('board/', include('apps.board.urls')),
    path('admin2/', include('apps.admin2.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/header/header.html
{% load static %}
		<div id="headerWrap">
			<div id="header">
				<h1 id="logo"><a href="#"><img src="{% static 'img/layout/logo.png' %}" alt="서울대학교 병원" /></a></h1>
				<!-- gnbWrap :s -->
                {% include "include/navigation_bar/gnb.html" %}
				<!-- gnbWrap :e -->

				<div id="globalWrap">
					<ul class="global">
						<li>안녕하세요. {{ user.id }}님</li>
						<li><a href="{% url 'account:modify' %}"> 회원정보수정</a></li>
						<li><a href="{% url 'index:logout' %}"> 로그아웃</a></li>
					</ul>
				</div>
			</div>
		</div>

templates/include/header/header_main.html
		<div id="header">
			<h1><a href="#" class="sp h_logo" ></a></h1>
		</div>