apps/admin2/urls.py
from apps.admin2 import views
from django.urls import path

app_name = 'admin2'

urlpatterns = [
    path('user_list/', views.user_list, name='user_list'),
]

apps/board/urls.py
from apps.board import views
from django.urls import path

app_name = 'board'

urlpatterns = [
    path('list/', views.list, name='list'),
    path('write/', views.write, name='write'),
    path('modify/<int:board_id>/', views.modify, name='modify'),
    path('read/<int:board_id>/', views.read, name='read'),
    path('delete/<int:board_id>/', views.delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.index.urls')),
    path('account/', include('apps.account.urls')),
    path('board/', include('apps.board.urls')),
    path('admin2/', include('apps.admin2.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/navigation_bar/gnb.html
{% load filters %}
				<div id="gnbWrap">
					<div id="gnb">
						<ul class="menu">
                            {% if user.is_staff %}
							<li><a href="#">사용자 관리</a>
								<ul class="sub">
									<li><a href="{% url 'admin2:user_list' %}">계정 관리</a></li>
								</ul>
							</li>
                            {% endif %}

							<li><a href="#">게시판 관리</a>
								<ul class="sub">
									<li><a href="{% url 'board:list' %}">공지사항</a></li>
									<li><a href="{% url 'board:list' %}">자유게시판</a></li>
								</ul>
							</li>
						</ul>
					 </div>
			 	</div>

templates/include/navigation_bar/lnb_admin.html
			<div id="lnbWrap">
				<div id="lnb_title">
					<h2>사용자 관리</h2>
				</div>
				<ul id="lnb">
					<li class="on"><a href="{% url 'admin2:user_list' %}">계정 관리</a></li>
				</ul>
			</div>

templates/include/navigation_bar/lnb_board.html
			<div id="lnbWrap">
				<div id="lnb_title">
					<h2>게시판</h2>
				</div>
				<ul id="lnb">
					<li class="on"><a href="{% url 'board:list' %}">공지사항</a></li>
					<li ><a href="{% url 'board:list' %}">자유게시판</a></li>
				</ul>
			</div>