apps/account/urls.py
from apps.account import views
from django.urls import path

app_name = 'account'

urlpatterns = [
    path('agree/', views.agree, name='agree'),
    path('register/', views.register, name='register'),
    path('modify/', views.modify, name='modify')
]

apps/board/urls.py
from apps.board import views
from django.urls import path

app_name = 'board'

urlpatterns = [
    path('list/', views.list, name='list'),
    path('write/', views.write, name='write'),
    path('modify/<int:board_id>/', views.modify, name='modify'),
    path('read/<int:board_id>/', views.read, name='read'),
    path('delete/<int:board_id>/', views.delete, name='delete'),
]

apps/index/urls.py
from django.urls import path, include
from apps.index import views
from django.contrib.auth import views as auth_views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='login_form.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('choose_function/', views.choose_function, name='choose_function')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.index.urls')),
    path('account/', include('apps.account.urls')),
    path('board/', include('apps.board.urls')),
    path('admin2/', include('apps.admin2.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/choose_function_form.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<meta http-equiv="Content-Style-Type" content="text/css">
{% load filters %}
{% load static %}
<link rel="shortcut icon" href="{% static 'img/logo.png' %}">
<title>Sumin Lecture</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/choose_func.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
<script src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#patient").on('click', function() {
            alert('준비중입니다.');
        });
    });
</script>
</head>
<body>
<!-- wrap :s -->
	<div id="wrap">
		<!-- header :s -->
        {% include "include/header/header_main.html" %}
		<!-- header :e -->

		<!-- container :s -->
		<div id="container">
			<div id="content">
				<h4 class="hide">기능 선택</h4>
                {% if user|has_group:'doctor' %}
                <a class="btn_wrap2" href="{% url 'board:list' %}">
                    <span class="horizontal_align">
                        <p><img src="{% static '/img/doctor.png' %}"></p>의사<b>Doctor</b>
                    </span>
                </a>
                {% endif %}
                {% if user|has_group:'patient' %}
                <a class="btn_wrap" id="patient">
                    <span class="horizontal_align">
                        <p><img src="{% static '/img/medicine.png' %}"></p>환자<b>Patient</b>
                    </span>
                </a>
                {% endif %}
			</div>
			
		</div>
		<!-- container :e -->

		<!-- footer :s -->
        {% include "include/footer/footer_main.html" %}
		<!-- footer :e	 -->

	

	</div>
<!-- wrap :e -->

</body>
</html>

templates/login_form.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<meta http-equiv="Content-Style-Type" content="text/css">
{% load static %}
<link rel="shortcut icon" href="{% static 'img/logo.png' %}">
<title>Sumin Lecture</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/signIn.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">

{#<script src="{% static 'js/jquery.min.js' %}"></script>#}
{#<script type="text/javascript">#}
{#    $(document).ready(function () {#}
{#    })#}
{#</script>#}
</head>
<body>
<!-- wrap :s -->
	<div id="wrap">
		<!-- header :s -->
		<div id="header">
			<h1><a href="#" class="sp h_logo" ></a></h1>
		</div>
		<!-- header :e -->

		<!-- container :s -->
		<div id="container">
			<div id="content">
				<form action="{% url 'index:login' %}" method="post">
					<fieldset class="findif_form">
						<legend class="blind">Sign In</legend>

						<label for="id" class="error"></label>
						<div class="input_row" id="id_area">
							<span class="input_box">
								<label for="id" id="label_id_area" class="lbl">ID</label>
								<input type="text" name="username"  placeholder="ID" class="int" maxlength="30" value="">
							</span>
						</div>
						<label for="pw" class="error"></label>
						<div class="input_row" id="pw_area">
							<span class="input_box">
								<label for="pw" id="label_pw_area" class="lbl">Password</label>
								<input type="password" name="password"  placeholder="Password" class="int" maxlength="30" >
							</span>
						</div>
						
						<div class="login_check">
							<span class="login_check_box">
								<input type="checkbox" id="login_chk" name="nvlong" class="" tabindex="9" value="off" onchange="savedLong(this);nclks_chk('login_chk', 'log.keepon', 'log.keepoff',this,event)" onclick="msieblur(this);">
								<label for="login_chk" id="label_login_chk" class="sp">아이디 저장</label>
							</span>
						</div>
                        {% if next %}
                        <div style="color: red">
                            <strong>권한이 없습니다.</strong>
                        </div>
                        {% endif %}
                        {% include 'include/form_errors.html' %}
						<input type="submit" id="btn_login" title="로그인" alt="로그인" value="로그인" class="btn_login" onclick=" ">
						
						<div class="find_info">
							<ul>
								<li><a href="{% url 'account:agree' %}">회원가입</a></li>
							</ul>
						</div>
					</fieldset>
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    {% csrf_token %}
                </form>
			</div>
		</div>
		<!-- container :e -->

		<!-- footer :s -->
		{% include "include/footer/footer_main.html" %}
		<!-- footer :e	 -->

	

	</div>
<!-- wrap :e -->

</body>
</html>