apps/board/urls.py
from apps.board import views
from django.urls import path

app_name = 'board'

urlpatterns = [
    path('list/', views.list, name='list'),
    path('write/', views.write, name='write'),
    path('modify/<int:board_id>/', views.modify, name='modify'),
    path('read/<int:board_id>/', views.read, name='read'),
    path('delete/<int:board_id>/', views.delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.index.urls')),
    path('account/', include('apps.account.urls')),
    path('board/', include('apps.board.urls')),
    path('admin2/', include('apps.admin2.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/board/models.py
from apps.account.models import MyUser
from apps.board.validators import max_file_size
from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver


class Board(models.Model):
    title = models.CharField(max_length=50)
    writer = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='writer')
    attachment = models.FileField(validators=[max_file_size], null=True, blank=True)
    content = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)


@receiver(post_delete, sender=Board)
def file_delete_action(sender, instance, **kwargs):
    instance.attachment.delete(False)


@receiver(pre_save, sender=Board)
def pre_save_attachment(sender, instance, *args, **kwargs):
    """ instance old attachment file will delete from os """
    try:
        old_attachment = instance.__class__.objects.get(id=instance.id).attachment.path
        try:
            new_attachment = instance.attachment.path
        except:
            new_attachment = None
        if new_attachment != old_attachment:
            import os
            if os.path.exists(old_attachment):
                os.remove(old_attachment)
    except:
        pass

apps/board/forms.py
from apps.board.models import Board
from django import forms


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board  # 사용할 모델
        fields = ['title', 'attachment', 'content']
        labels = {
            'title': '제목',
            'attachment': '첨부파일',
            'content': '내용',
        }

apps/board/views.py
from apps.board.decorators import is_writer
from apps.board.forms import BoardForm
from apps.board.models import Board
from django.contrib.auth.decorators import permission_required, login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, resolve_url, redirect
from etc.utils import get_first_error_message


@login_required
@permission_required(perm='board.view_board')
def list(request):
    page = request.GET.get('page', '1')  # 페이지
    per_page = request.GET.get('per_page', '10')  # 페이지당 게시글 수
    option = request.GET.get('option')  # 검색옵션
    keyword = request.GET.get('keyword')  # 검색어

    board_list = Board.objects.order_by('-pk')

    if option and keyword:  # 검색기준
        if option == 'content':  # 내용
            q = Q(content__icontains=keyword)
        elif option == 'title+content':  # 제목+내용
            q = Q(title__icontains=keyword) | \
                Q(content__icontains=keyword)
        elif option == 'writer':  # 작성자
            q = Q(writer__username__icontains=keyword)
        else:  # 제목
            q = Q(title__icontains=keyword)
        board_list = board_list.filter(q).distinct()

    # 페이징처리
    paginator = Paginator(board_list, per_page)
    page_obj = paginator.get_page(page)

    context = {'board_list': page_obj, 'keyword': keyword, 'option': option}
    return render(request, 'board/board_list.html', context)


@login_required
@permission_required(perm='board.view_board')
def read(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    return render(request, 'board/board_read.html', {'board': board})


@login_required
@permission_required(perm='board.add_board')
def write(request):
    if request.method == 'GET':
        return render(request, 'board/board_write.html')
    if request.method == 'POST':
        form = BoardForm(request.POST, request.FILES)
        if form.is_valid():
            board = form.save(commit=False)
            board.writer = request.user
            board.save()
            context = {'redirect': resolve_url('board:read', board.id)}
            return JsonResponse(context)
        else:
            msg = get_first_error_message(form.errors.items())
            context = {'msg': msg}
            return JsonResponse(context, status=401)


@login_required
@is_writer
@permission_required(perm='board.change_board')
def modify(request, board):
    if request.method == 'GET':
        return render(request, 'board/board_write.html', {'board': board})
    elif request.method == 'POST':
        form = BoardForm(request.POST, request.FILES, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            board.save()

            context = {'redirect': resolve_url('board:read', board.id)}
            return JsonResponse(context)
        else:
            msg = get_first_error_message(form.errors.items())
            context = {'msg': msg}
            return JsonResponse(context, status=401)


@login_required
@is_writer
@permission_required(perm='board.delete_board')
def delete(request, board):
    board.delete()
    return redirect('board:list')

templates/board/board_list.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<meta http-equiv="Content-Style-Type" content="text/css">
{% load filters %}
{% load static %}
<link rel="shortcut icon" href="{% static 'img/logo.png' %}">
<title>Sumin</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.3.custom.min.js' %}"></script>
<script src="{% static 'js/submenu.js' %}"></script>
<script type="text/javascript">
	$(document).ready(function () {
		$("#writeBtn").on('click', function() {
			location.href='{% url 'board:write' %}';
		});
	});
</script>
</head>

<body>
<!-- wrap :s -->
	<div id="wrapper">

		<!-- header :s -->
		{% include "include/header/header.html" %}
		<!-- header :e -->


		<!-- contentsWrap :s -->
		<div id="contentsWrap">

			<!-- lnbWrap :s -->
            {% include 'include/navigation_bar/lnb_board.html' %}
			<!-- lnbWrap :e -->

			<!-- container :s -->
			<div id="container">

				<div class="location">
					<span class="home"><a href="#"><img src="{% static 'img/layout/ico_home.png' %}" alt="홈"></a></span>
					<span class="arrow">&gt;</span>
					<a href="#"> <span class="first">게시판</span></a>
					<span class="arrow">&gt;</span>
					<a href="#"> <span>공지사항</span></a>
				</div>

				<h3 id="contTi">공지 사항</h3>

				<!-- 컨텐츠영역 txt :s -->
				<div id="txt">
					
					<h4>공지사항</h4>
					<!-- table :s -->
					<table class="tbl_basic" style="table-layout:fixed;">
			            <caption>
			                <strong>공지사항</strong>
			                <details>
			                    <summary>공지사항</summary>
			                </details>
			            </caption>
		                <thead>
		                    <tr>
		                        <th class="trw" width=30>No</th>
		                        <th class="trw">제목</th>
		                        <th class="trw" width=100>작성자</th>
		                        <th class="trw" width=120>작성일</th>
		                    </tr>
		                </thead>
		                <tbody>
                        {% for board in board_list %}
							<tr>
								<td>{{ board.id }}</td>
								<td><a href="{% url 'board:read' board_id=board.id %}">{{ board.title }}</a></td>
								<td>{{ board.writer }}</td>
								<td>{{ board.created_at|format_datetime:'%Y년 %m월 %d일' }}</td>
							</tr>
                        {% endfor %}
		                </tbody>
		            </table>
		            <!-- table :e -->
					
		            <!-- paging :s -->
                    {% with page_list=board_list url='board:list' %}
                        {% include 'include/paginate.html' %}
                    {% endwith %}
                    <!-- paging :e -->

                    <!-- search :s -->
					<div id="searchtab">
					<form class="search_info" style="background: #ffffff">
					<li>
						<select id="searchOption" name="option" class="searchOption">
							<option value="title" >제목</option>
							<option value="content" >내용</option>
							<option value="title+content" >제목+내용</option>
							<option value="writer" >작성자</option>
						</select>
                        <input type="hidden" name="per_page" value="{{ board_list.paginator.per_page }}">
						<input type="text" name="keyword" class="inputText" value="{{ keyword|default_if_none:'' }}"
                               class="inputText" placeholder="조건 입력"/>
						<input type="submit" id="searchButton" class="submitbtn" value="검색" class="searchBtn"/>
					</li>
					</form>
					</div>
		            <!-- search :e -->
					<span class="rightButton" >
						<button id="writeBtn" type="button" class="mainbtn">게시판 작성</button>
					</span>
				</div>
				<!-- 컨텐츠영역 txt :e -->

			</div>
			<!-- container :e -->

		</div>
		<!-- contentsWrap :e -->

		
		<!-- footerWrap :s -->
		{% include "include/footer/footer.html" %}
		<!-- footerWrap :e -->
	</div>
</body>
</html>

templates/board/board_read.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<meta http-equiv="Content-Style-Type" content="text/css">
{% load static %}
<link rel="shortcut icon" href="{% static 'img/logo.png' %}">
<title>Sumin</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.3.custom.min.js' %}"></script>
<script src="{% static 'js/submenu.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function () {
		$("#modifyBtn").on('click', function() {
			location.href='{% url 'board:modify' board.id %}';
		});

		$("#deleteBtn").on('click', function() {
			location.href='{% url 'board:delete' board.id %}';
		});

		$("#listBtn").on('click', function() {
			location.href='{% url 'board:list' %}';
		});
	});
</script>
</head>

<body>
<!-- wrap :s -->
	<div id="wrapper">

		<!-- header :s -->
		{% include "include/header/header.html" %}
		<!-- header :e -->


		<!-- contentsWrap :s -->
		<div id="contentsWrap">

			<!-- lnbWrap :s -->
            {% include 'include/navigation_bar/lnb_board.html' %}
			<!-- lnbWrap :e -->

			<!-- container :s -->
			<div id="container">

				<div class="location">
					<span class="home"><a href="#"><img src="{% static 'img/layout/ico_home.png' %}" alt="홈"></a></span>
					<span class="arrow">&gt;</span>
					<a href="#"> <span class="first">게시판</span></a>
					<span class="arrow">&gt;</span>
					<a href="#"> <span>게시판 작성</span></a>
				</div>

				<h3 id="contTi">게시판 작성</h3>

				<!-- 컨텐츠영역 txt :s -->
				<div id="txt">
					
					<h4>게시판 작성</h4>
					<!-- table :s -->
					<table class="tbl_basic" style="table-layout:fixed;">
			            <caption>
			                <strong>게시판 작성</strong>
			                <details>
			                    <summary>게시판 내용</summary>
			                </details>
			            </caption>
		                <tbody>
							<tr>
								<td class="trw" width="200">제목</td>
								<td>
									{{ board.title }}
								</td>
							</tr>
							<tr>
								<td class="trw" width="200">작성자</td>
								<td style="text-align: left;">
									{{ board.writer }}
								</td>
							</tr>
                            <tr>
                                {% if board.attachment %}
                                <td class="trw" width="200">첨부파일</td>
                                <td>
                                    <a href="{{ board.attachment.url }}" download>{{ board.attachment.name }}</a>
                                </td>
                                {% endif %}
							</tr>
							<tr>
								<td class="trw" width="200" height="400">내용</td>
								<td style="text-align: left; vertical-align: top;">
									{{ board.content }}
								</td>
							</tr>
		                </tbody>
		            </table>
		            <!-- table :e -->
					
		            <!-- paging & search :s -->
                    {% if user == board.writer %}
					<input type="button" value="수정" class="subbtn3" id="modifyBtn">
					<input type="button" value="삭제" class="subbtn3" id="deleteBtn">
                    {% endif %}
					<span class="rightButton" >
						<button type="button" id="listBtn" class="mainbtn">목록</button>
					</span>
		            <!-- paging & search :e -->
				</div>
				<!-- 컨텐츠영역 txt :e -->

			</div>
			<!-- container :e -->

		</div>
		<!-- contentsWrap :e -->

		
		<!-- footerWrap :s -->
		{% include "include/footer/footer.html" %}
		<!-- footerWrap :e -->
	</div>
</body>
</html>

templates/board/board_write.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<meta http-equiv="Content-Style-Type" content="text/css">
{% load static %}
<link rel="shortcut icon" href="{% static 'img/logo.png' %}">
<title>Sumin</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.3.custom.min.js' %}"></script>
<script src="{% static 'js/submenu.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function () {
		$("#submit").on('click', function() {
			write();
		});
		$("#cancelBtn").on('click', function() {
			cancel();
		});
	});

	function write() {
		$.ajax({
			type: "POST",
			data: new FormData($("#writeFrm")[0]),
            headers:{
              'X-CSRFTOKEN':'{{ csrf_token }}'
            },
			processData: false,
			contentType: false,
			success: function(data){
				location.href=data.redirect;
			},
			error: function(err){
	            alert(err.responseJSON.msg);
			}
		});
	}
	function cancel() {
		if(location.pathname.indexOf('modify') == -1)
			location.href='/board/list';
		else
			location.href='/board/read?bid=' + $('input[name=bid]').val();;
	}
</script>
</head>

<body>
<!-- wrap :s -->
	<div id="wrapper">

		<!-- header :s -->
		{% include "include/header/header.html" %}
		<!-- header :e -->


		<!-- contentsWrap :s -->
		<div id="contentsWrap">

			<!-- lnbWrap :s -->
            {% include 'include/navigation_bar/lnb_board.html' %}
			<!-- lnbWrap :e -->

			<!-- container :s -->
			<div id="container">

				<div class="location">
					<span class="home"><a href="#"><img src="{% static 'img/layout/ico_home.png' %}" alt="홈"></a></span>
					<span class="arrow">&gt;</span>
					<a href="#"> <span class="first">게시판</span></a>
					<span class="arrow">&gt;</span>
					<a href="#"> <span>게시판 작성</span></a>
				</div>

				<h3 id="contTi">게시판 작성</h3>

				<!-- 컨텐츠영역 txt :s -->
				<div id="txt">

					<form id="writeFrm" enctype="multipart/form-data">
                        <h4>게시판 작성</h4>
                        <!-- table :s -->
                        <table class="tbl_basic" style="table-layout:fixed;">
                            <caption>
                                <strong>게시판 작성</strong>
                                <details>
                                    <summary>게시판 내용</summary>
                                </details>
                            </caption>
                            <tbody>
                                <tr>
                                    <td class="trw" width="200">제목</td>
                                    <td>
                                        <input class="inputText2" type="text" name="title" style="width:100%"
                                            value="{{ board.title|default_if_none:'' }}">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="trw" width="200">작성자</td>
                                    <td style="text-align: left;">
                                        {{ board.writer|default_if_none:'' }}
                                    </td>
                                </tr>
                                <tr>
                                    <td class="trw" width="200">파일</td>
                                    <td style="text-align: left;">
                                        <input class="inputText2" type="file" name="attachment" style="width:100%">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="trw" width="200">내용</td>
                                    <td>
                                        <textarea name="content" rows="30" cols="100"
                                            >{{ board.content|default_if_none:'' }}</textarea>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <!-- table :e -->

                        <!-- paging & search :s -->
                        <input type="button" id="cancelBtn" value="취소"  class="subbtn3">
                        <input type="reset" value="다시하기" class="subbtn3">
                        <span class="rightButton" >
                            <button type="button" id="submit" class="mainbtn">저장하기</button>
                        </span>
                        <!-- paging & search :e -->
                        {{ form.csrf_token }}
                    </form>
				</div>
				<!-- 컨텐츠영역 txt :e -->

			</div>
			<!-- container :e -->

		</div>
		<!-- contentsWrap :e -->

		
		<!-- footerWrap :s -->
		{% include "include/footer/footer.html" %}
		<!-- footerWrap :e -->
	</div>
</body>
</html>